apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: createec2-workflow
  namespace: argo
spec:
  entrypoint: createec2-workflow
  ttlStrategy:
    secondsAfterSuccess: 1800 # 30 minutes
  volumes:
    - name: secret-vol
      secret:
        secretName: aws-creds
  templates:
    - name: createec2-workflow
      metadata:
      container:
        image: "160878852983.dkr.ecr.us-west-2.amazonaws.com/python:latest"
        imagePullPolicy: IfNotPresent
        command: [ "python", "./createec2.py" ]
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: "aws-creds"
                key: "id"
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "aws-creds"
                key: "key"